version: 2
jobs:
  ping_swiftirc:
    machine: true
    shell: bash
    steps:
      - run: mkdir -p logs/{curl,ping,netcat}
      - run: 
          command: curl -iL swiftirc.net > logs/curl/swiftirc.net.log
          when: always
      - run: 
          command: curl -iL www.swiftirc.net > logs/curl/www.swiftirc.net.log
          when: always
      - run: 
          command: curl -iL qwebirc.swiftirc.net > logs/curl/qwebirc.swiftirc.net.log
          when: always
      - run: 
          command: for a in $(dig A +short irc.swiftirc.net) ; do ping -c5 $a > logs/ping/$a.log ; done
          when: always
      - run: 
          command: for a in $(dig A +short irc.swiftirc.net) ; do nc -w1 $a 6667 > logs/netcat/$a.log 2>&1 ; done
          when: always
# CircleCI does not have IPv6 connectivity .........
# TODO: workaround?
#      - run: for a in $(dig AAAA +short irc.swiftirc.net) ; do ping6 -c5 $a > logs/ping/$a.log ; done
      - run:
          command: find logs/ -exec cat {} \;
          when: always
      - store_artifacts:
          path: logs

workflows:
  version: 2
  ping:
    jobs:
      - ping_swiftirc
    triggers:
      - schedule:
          cron: "0,10,20,30,40,50 * * * *"
          filters:
            branches:
              only:
                - master
